### PR TITLE
Merge with Nanashi-Meiyo-Meijin lyra2v2 algorythm

### PR DESCRIPTION
**Pull request by Myrinia**

### CODE REVIEW

**Comment by l0gicgate** [comment]
Thanks for this pull request @Myrinia I've been waiting for someone to do this! I get an extra 10MH/s on my 1080ti with his miner, however it has a trojan in it. 

*Edit: The miner I'm referring to was compiled by Crypto-Mining Blog, not directly from Nanashi-Meiyo-Meijin's repo.

**Comment by h-town** [comment]
@l0gicgate trojan......wut?  rather serious accusation....what say you as to your evidence to support this claim?

**Comment by l0gicgate** [comment]
@h-town I'm referring to the miner downloaded here:
http://cryptomining-blog.com/9166-latest-ccminer-2-2-fork-by-nanashi-meiyo-meijin-for-monacoin-mining/

Sorry if my comment was unclear. Windows Defender automatically deletes it and it is labelled a severe threat.

**Comment by kkkrackpot** [comment]
@l0gicgate Just delete that shit named "Windows Defender"...
@Myrinia where is Nahashi-Meiyo-Mejin's original git repo?

**Comment by 7h3Cub3** [comment]
here

https://github.com/Nanashi-Meiyo-Meijin/ccminer/releases

And indeed cryptominingblog version compiled without the static libraries was flagged, but the original binaries from nanashi github are unflagged. They probably used some exe compressing shit that make most AV ring bells.

**Comment by Myrinia** [comment]
Close this one and use this one :)

https://github.com/tpruvot/ccminer/pull/33

**Pull request closed without merging**
