### PR TITLE
~10% speedup

### PR DESCRIPTION
**Pull request by pallas1**
Untested on ARCH < 5.2

### CODE REVIEW

**Comment by tpruvot** [comment]
ok, merged, thanks :+1:

**Comment by chappjc** [comment]
On a GTX 980 in Win 7 x64, decred occupancy and performance actually went down by about that amount.  But with `__launch_bounds__(2*TPB,3)` on `blake256_gpu_hash_nonce` it a little better, just shy of 2 Ghash/s, which is a 2% increase over last version.  Turned out as 115 registers for sm_50/sm_52, but with spills on sm_30.  I'm not sure maxregisters of 80 is still optimal for decred.cu.

Bring on Pascal and all those registers!  :)

**Comment by tpruvot** [comment]
indeed that could explain the difference, 128 regs seems to be optimal

**Comment by chappjc** [comment]
Planning to test on slower sm_30 card.

**Comment by tpruvot** [comment]
just pushed the last commits to optimize the speed on windows too

**Pull request closed without merging**
