### PR TITLE
Update ccminer.vcxproj

### PR DESCRIPTION
**Pull request by XhmikosR**
This is untested.

Added `/RELEASE` and removed individual unneeded conditions. If those are needed I can revert them.

### CODE REVIEW

**Comment by tpruvot** [comment]
feel free to do what you want... but not needed

**Comment by XhmikosR** [comment]
Nice approach.

**Comment by djm34** [comment]
I second XhmikosR idea 😄

**Comment by tpruvot** [comment]
my releases use upx to reduce the binary size, which make this checksum bad

**Pull request closed without merging**
