### PR TITLE
Remove comment that prevent compilation on japanese windows

### PR DESCRIPTION
**Pull request by LysanderGG**

### CODE REVIEW

**Comment by tpruvot** [comment]
are you japanese ? is the text readable here ?

**Comment by sukoshi1507** [comment]
It is.

Le sam. 6 janv. 2018 à 11:18, Tanguy Pruvot <notifications@github.com> a
écrit :

**Comment by LysanderGG** [comment]
Not japanese but living in Japan.
The text is readable, the encoding is correct but I suspect that the last 2-byte character finishes as a "\\" character. Couldn't verify it here though as I don't have a japanese pc here but last time I compiled on it the next line was escaped (adding another character at the end of the comment would also fix the problem).

**Comment by LysanderGG** [comment]
A few complementary info:
- the file encoding is utf8 without BOM
- the comments finish by "る", if I add another character after the file compile without problem.
- the utf8 encoding of the character is 0x e3 82 8b
- I have the following warning so I suppose the files are compiled as shift-jis C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss. 

Changing the file encoding to Shift-JIS or utf8 with BOM also fixed the compile error.

**Comment by hakemimi** [comment]
Useful notes for porting foreign codes:

- The VC++ compiler command will *not* recognize UTF-8 (without BOM) source files in any ways. This is due to historical reasons and it is totally by design
- Please don't use CP932 or Shift-JIS or UTF-8 (BOM) or whatever Windows-friendly encoding *even if* you have multi-byte letters in your source code
- git can totally manage these Windows-specific problem by specifying appropriate config to `.gitattributes`

**Pull request merged**
