### PR TITLE
CUDA Compatibility Document

### PR DESCRIPTION
**Pull request by paulmadore**
Spent the majority of my day perplexed. Figured it out eventually. This table would have helped me to make my compile right the first time.

### CODE REVIEW

**Comment by tpruvot** [comment]
ccminer -n

**Comment by paulmadore** [comment]
Oh, that outputs the compatible CUDA version, does it? My mistake.

**Comment by tpruvot** [comment]
Yes, and even if most are correct, most office/small cards often have different versions ;) adding a list in ccminer will just ... be hard to maintain. The wiki seems better for that

**Comment by tpruvot** [comment]
https://github.com/tpruvot/ccminer/wiki/Compatibility

**Pull request closed without merging**
